default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_fun_development
test:
  <<: *default
  database: rails_fun_test
production:
  <<: *default
  database: rails_fun_production
  username: #Set these when you deploy
  password:
